config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  root 'users#index'
  get 'users/new'
  get 'users/create'
  get 'tasks/index'
  get 'tasks/new'
  get 'users/login_form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login', to:'users#login'
  post 'users/create', to:'users#create'
  post 'tasks/create', to:'tasks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(user_id: session[:id])
    # @tasks =  Task.find_by(user_id: session[:id])
  end

  def new
    # @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
        redirect_to tasks_index_path
      else
        render("tasks/index")
    end
  end

  private
    def task_params
      params.permit(:user_id,:taskname,:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "User registration has been completed."
        @current_user = @user
        redirect_to root_path
      else
        render("users/new")
      end
  end

  def login

      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:notice] = "Logged in"
        @@ids = @user.id
        session[:id] = @user.id
        redirect_to tasks_index_path
      else
        @error_message = "Your email or username is incorrect."
        @email = params[:email]
        @password = params[:password]
        render("users/login_form")
      end
  end

  private
    def user_params
      params.permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>
<h1><%= session[:id] %></h1>

<% @tasks.each do |task| %>
    <tr>
      <td>こんにちは<%= task.user_id %>さん</td>
      <td><%= task.taskname %></td>
      <td><%= task.body %></td>
    </tr>
    <br>
<% end %>
<br>
<%= link_to 'タスク登録',tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create to Your Task</h1>
  <p>Please fill in this form to create an account.</p

  <h1><%= session[:id] %></h1>
  <%= form_with url: tasks_create_path, local: true do |form| %>
    <%= form.label :taskname %>
    <li>
      <%= form.text_field :taskname %>
    </li>
    <%= form.label :body %>
    <li>
      <%= form.text_field :body %>
    </li>

    <li>
      <%= form.text_field :user_id ,value: session[:id]%>
    </li>
    <% session[:user_id] = session[:id]  %>

    <%= form.submit "Create my account", class: "btn btn-primary" %>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= link_to '新規登録' ,users_new_path %>
<%= link_to 'ログイン' ,users_login_form_path %>

app/views/users/login_form.html.erb
<h1>Log in</h1>
  <p>Please fill in this form to log in.</p>
  <%= form_with url:login_path, local: true do |form| %>
    <%= form.label :name %>
    <li>
      <%= form.text_field :name %>
    </li>
    <%= form.label :email %>
    <li>
      <%= form.email_field :email %>
    </li>
    <%= form.label :password %>
    <li>
      <%= form.password_field :password %>
    </li>
    <%= form.label :password_confirmation, "Confirmation" %>
    <li>
      <%= form.password_field :password_confirmation %>
    </li>
    <%= form.submit "Log in", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <p>Please fill in this form to create an account.</p>
  <%= form_with url: users_create_path, local: true do |form| %>
    <%= form.label :name %>
    <li>
      <%= form.text_field :name %>
    </li>
    <%= form.label :email %>
    <li>
      <%= form.email_field :email %>
    </li>
    <%= form.label :password %>
    <li>
      <%= form.password_field :password %>
    </li>
    <%= form.label :password_confirmation, "Confirmation" %>
    <li>
      <%= form.password_field :password_confirmation %>
    </li>
    <%= form.submit "Create my account", class: "btn btn-primary" %>
  <% end %>